<?php

namespace Fduh\PokerBundle\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\ORM\EntityRepository;

/**
 * EventRepository.
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EventRepository extends EntityRepository
{
    /**
     * returns all events from the season $season ordered by date, asc.
     *
     * @param Season $season
     *
     * @return Collection
     */
    public function findViewableEventsByDateAsc(Season $season)
    {
        return $this->getEntityManager()
            ->createQuery(
                'SELECT e, r, s, p FROM FduhPokerBundle:Event e
                JOIN e.results r
                JOIN e.season s
                JOIN r.player p
                WHERE e.season = (:season)
                AND e.viewable = (:viewable)
                ORDER BY e.date ASC'
            )
            ->setParameter('season', $season)
            ->setParameter('viewable', true)
            ->getResult();
    }

    public function findAllViewableEventsByDateAsc()
    {
        $results = $this->getEntityManager()
            ->createQuery(
                'SELECT e, r, p FROM FduhPokerBundle:Event e
                JOIN e.results r
                JOIN r.player p
                WHERE e.viewable = (:viewable)
                ORDER BY e.date ASC'
            )
            ->setParameter('viewable', true)
            ->getResult();
        
        return new ArrayCollection($results);
    }
}
