<?php

namespace Fduh\PokerBundle\Entity;

use Doctrine\ORM\EntityRepository;
use Fduh\PokerBundle\Entity\Player;
use Fduh\PokerBundle\Entity\Season;

/**
 * ResultRepository.
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ResultRepository extends EntityRepository
{
}
